### ISSUE TITLE
What could be causing slow reloads

### ISSUE THREAD

**Issue by anubhavg8** [barrel/shopify-vite#102]
Hi there! it's me again. I was wondering if their is any reason reloads are pretty slow? 20seconds>? Have uninstalled - installed and updated the cli. 

![issue](https://github.com/barrel/shopify-vite/assets/22794870/46bf17d5-d85a-4df7-9462-630627bb19b0)

**Comment by montalvomiguelo** [comment]
@anubhavg8!, Thanks for reaching out. Your issue might be with the CLI rather than this project. Could you open an issue in the CLI repository for more targeted assistance?
Best regards.
