### ISSUE TITLE
[Fly.io] - Vite is running localhost:5173 on production

### ISSUE THREAD

**Issue by mason2205** [barrel/shopify-vite#103]
I'm facing with an problem when deploy shopify app using vite on fly.io, it's running the localhost:5173 on production. Do we have any configure when build & deploy it as working without localhost?
![image](https://github.com/barrel/shopify-vite/assets/142089536/e8139ba0-0c44-410e-85d9-2ac09f76ad71)

**Comment by montalvomiguelo** [comment]
Try building prod-ready assets 'vite build' before pushing to production?

**Comment by montalvomiguelo** [comment]
Be sure your store loads the prod version of your them extension?

**Comment by huykon** [comment]
@montalvomiguelo yes I'm load the prod version of my theme extension. Do we need any config for vite build?

**Comment by mason2205** [comment]
@montalvomiguelo  yes I'm loading the prod version of my theme extension. Do we need any config for vite build?

**Comment by mason2205** [comment]
@montalvomiguelo any help? why did you close this issue while we haven't solution for it?

**Comment by montalvomiguelo** [comment]
@mason2205 The generated output/assets look good; your issue is unrelated to this Plugin. If it's a deployment issue, the Shopify CLI handles that.
