### ISSUE TITLE
Possible CORS errors in Console

### ISSUE THREAD

**Issue by ConduciveMammal** [barrel/shopify-vite#104]
When running the server, I get a bunch of CORS errors, both for my own files and Shopify files.

For my files, I find I need to open the link, accept the security notice and then reload to get rid of those CORS errors.

Is this expected?

![CleanShot 2023-10-25 at 9  46 28@2x](https://github.com/barrel/shopify-vite/assets/18140157/b736170c-bbfe-41a0-9bc8-39c53373c189)

**Comment by montalvomiguelo** [comment]
@ConduciveMammal, Thanks for reaching out. The CORS errors might be related to the Shopify CLI rather than this Plugin. I recommend that you share this in the Shopify CLI repo for help with this specific issue.
