### ISSUE TITLE
Handle external scripts in dev

### ISSUE THREAD

**Issue by james0r** [barrel/shopify-vite#107]
I'm not seeing how I would handle copying external scripts during dev. I tried https://www.npmjs.com/package/vite-plugin-static-copy but this also doesn't copy scripts when changed/added in dev.

The assets directory is cleaned out on build so they also can't be added there.

**Comment by james0r** [comment]
Put together a little plugin that seems to be doing the trick

```javascript
import shopify from 'vite-plugin-shopify'
import pageReload from 'vite-plugin-page-reload'
import basicSsl from '@vitejs/plugin-basic-ssl'
import { watch } from 'chokidar';
import fs from 'fs-extra'

const watchStaticAssets = () => ({
  name: 'watch-static-assets',
  configureServer(server) {
    const watcher = watch('./public/*', {
      persistent: true
    });

    const copyAsset = async path => {
      await fs.copy(path, `assets/${path.replace('public/', '')}`);
    }

    const removeAsset = async path => {
      await fs.remove(`assets/${path.replace('public/', '')}`);
    }

    watcher.on('add', copyAsset);
    watcher.on('change', copyAsset);
    watcher.on('unlink', removeAsset);
  }
})

export default {
  clearScreen: false,
  server: {
    host: '127.0.0.1',
    https: true,
    port: 3000
  },
  publicDir: true,
  plugins: [
    basicSsl(),
    watchStaticAssets(),
    shopify({
      snippetFile: 'vite.liquid'
    }),
    // pageReload('/tmp/theme.update', {
    //   delay: 2000
    // })
  ],
  build: {
    sourcemap: true,
    rollupOptions: {
      output: {
        entryFileNames: '[name].[hash].min.js',
        chunkFileNames: '[name].[hash].min.js',
        assetFileNames: '[name].[hash].min[extname]',
      },
    }
  }
}
```

**Comment by montalvomiguelo** [comment]
@james0r  Thanks for sharing!

Alternate approach, you can keep some files in the assets/ folder and configure Vite so it does not clear it.
https://vitejs.dev/config/build-options.html#build-emptyoutdir

_(You may also need to clean Vite generated assets https://shopify-vite.barrelny.com/guide/troubleshooting.html#how-to-cleanup-the-assets-folder)_

**Comment by james0r** [comment]
@montalvomiguelo I had that going before using the `.static.` prefix (borrowed from shopify theme labs). Was working fine but just wasn't as intuitive I felt.
