### ISSUE TITLE
Running shopify and vite servers in parallel does not work following guide

### ISSUE THREAD

**Issue by kyleruscigno** [barrel/shopify-vite#119]
**package.json:**

```
{
    "dev": "run-p -sr \"shopify:dev -- {@}\" \"vite:dev\" --",

    "build": "vite build",

    "deploy": "run-s \"build\" \"shopify:push -- {@}\" --",

    "shopify:dev": "shopify theme dev",

    "shopify:push": "shopify theme push",

    "vite:dev": "vite",

    "prettier": "prettier --write"
  }
```

If I try to run 'npm run dev' as outlined [here](https://shopify-vite.barrelny.com/guide/troubleshooting.html) the vite server successfully comes online, but the shopify server does not. Removing the \"vite:dev\" part of the command will successfully launch the shopify server when ran. I suspect I may just have a misunderstanding of how I should be using the npm run all command with argument passthrough... everything works fine when using 2 seperate terminals to run 'shopify theme dev' and 'vite' simultaneously. 

<img width="614" alt="image" src="https://github.com/barrel/shopify-vite/assets/22186622/800ec822-b756-4bf6-ab99-31ccdcf6d488">

**Comment by montalvomiguelo** [comment]
hi, could you try turning off the debugger?

**Comment by kyleruscigno** [comment]
<img width="510" alt="Screenshot 2024-02-27 095345" src="https://github.com/barrel/shopify-vite/assets/22186622/d29eb13a-4f3c-498a-8573-f72a3bdf20a7">

Same outcome, vite server launches but the shopify theme never does.

**Comment by montalvomiguelo** [comment]
I can't replicate the issue on my end. There's an alternate approach to launch both using concurrently instead of run-p https://github.com/montalvomiguelo/skeleton-theme/blob/develop/package.json#L19
