### ISSUE TITLE
@apply inside main.scss

### ISSUE THREAD

**Issue by danielehrhardt** [barrel/shopify-vite#129]
How can i use @apply inside the main.scss file?
![image](https://github.com/barrel/shopify-vite/assets/19570043/dbc272ed-461f-495e-9d6a-9126303dd0b9)

**Comment by montalvomiguelo** [comment]
https://tailwindcss.com/docs/using-with-preprocessors#sass

**Comment by montalvomiguelo** [comment]
Hi @danielehrhardt were you able to make it work?

**Comment by lspoor** [comment]
I believe this works fine if you remove the `!`, from what I've found you can't use the important rule with `@apply`.
