### ISSUE TITLE
Page not reloading with Solid

### ISSUE THREAD

**Issue by yayashn** [barrel/shopify-vite#130]
I've integrated Solid but any changes in `frontend/components/example.tsx` do not trigger a reload in the shopify server. Changes are only visible after I manually refresh. 

How can I configure the plugin to achieve reloads with Solid?

**Comment by montalvomiguelo** [comment]
@yayashn load the solid plugin?
https://github.com/montalvomiguelo/skeleton-theme/commit/49ee505250b9dc028c7887b33e16f7b9c0f2b110

**Comment by yayashn** [comment]
@montalvomiguelo I've already got Solid up and running, I'm saying the shopify page doesn't reload automatically when I edit any Solid `.tsx` files. Does it auto reload for you?

**Comment by montalvomiguelo** [comment]
@yayashn Yup, it reloads for me in the example above

**Comment by yayashn** [comment]
@montalvomiguelo Just tested the example and it does indeed work, I wonder if it's to do with `.tsx` files maybe? I'll share an example of my broken version.

**Comment by yayashn** [comment]
Can confirm `tsx` changes also work in the example, must have gone wrong somewhere in my setup I'll do a comparison but safe to assume nothing is broken.
