### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Ulset** [barrel/shopify-vite#131]
Im trying to migrate our existing theme-extensions to react, and ive just begin the testing process but it seems to not be working as expected.

Using this `vite.config.mjs`

```javascript
import { defineConfig } from 'vite'
import shopify from 'vite-plugin-shopify'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [
    shopify({
      themeRoot: 'extensions/theme-extensions',
      sourceCodeDir: 'frontend',
      entrypointsDir: 'frontend/entrypoints',
      snippetFile: 'vite.liquid'
    }),
    react(),
  ]
})
```

And this project structure:
<img width="398" alt="bilde" src="https://github.com/barrel/shopify-vite/assets/33099664/47a10653-2334-49e0-8267-472bccf896cf">

When i try to access the files i get the following error:
<img width="409" alt="bilde" src="https://github.com/barrel/shopify-vite/assets/33099664/a9e518df-c582-46be-b55b-4e64d29168e2">

This is the `test_thing.liquid` file, which should run the vite builded files
```liquid
<p>her</p>
<div id="test_root"></div>
{% liquid render 'vite' with 'entry.ts' as da %}

{% schema %}
{
  "name": "Test vite",
  "target": "section",
  "settings": [
    {
      "type": "checkbox",
      "id": "show_buy_now_button",
      "label": "Show 'buy now' button",
      "default": true
    }
  ]
}
{% endschema %}
```

Ive tested with both .ts, .tsx and .jsx files. All gets the same result.

Ive checked out most of the example repos, and it seems to me that i have the exact project structure as the others

**Comment by montalvomiguelo** [comment]
@Ulset see https://github.com/montalvomiguelo/theme-extension-vite

**Comment by Ulset** [comment]
@montalvomiguelo i have! Is it anything there in particular i should be aware of? Seems to be the same there aswell. Do i need to have a separate package.json file in the theme directory?

**Comment by Ulset** [comment]
Ive replicated your provided example

<img width="369" alt="bilde" src="https://github.com/barrel/shopify-vite/assets/33099664/814475f0-5b5f-4ec8-b477-9624d4f2a3f3">

Still the same error

**Comment by Ulset** [comment]
<img width="506" alt="bilde" src="https://github.com/barrel/shopify-vite/assets/33099664/b6b92ff6-f7e8-4b25-8632-9097c5c83977">

It seems to try to request a path to endpoints without anything more specified, is this expected behavior?

**Comment by montalvomiguelo** [comment]
@Ulset that is not expected; you need to provide an entry point; we don't support the "as" parameter.

The example I provided works fine. Pick the pieces you need from there?

https://github.com/barrel/shopify-vite/assets/5134470/9a78a90c-462b-4fa3-ab6f-a4302b4c8f4f

**Comment by Ulset** [comment]
My editor (IntelliJ) keeps complainting about the missing 'as' paramter.
<img width="505" alt="bilde" src="https://github.com/barrel/shopify-vite/assets/33099664/6d5de916-5fb0-473b-a11d-ce70d5aa4161">

But by removing the 'as' everything works as expected, thank you for the help!
