### ISSUE TITLE
 Get and update works without stopping

### ISSUE THREAD

**Issue by skomskiy** [barrel/shopify-vite#145]
Hello. I have a problem on all projects where Vite is installed. The sync doesn't stop. Get and update works without stopping. What could this be due to? Thanks
https://prnt.sc/F4SB9Aysd0Wq

**Comment by montalvomiguelo** [comment]
Shopify Vite does not sync files. Try using the latest version of the Shopify CLI?
https://github.com/Shopify/cli/releases/tag/3.63.2

**Comment by skomskiy** [comment]
It didn't help. 
The interesting thing is that no other projects without vite have this problem.

**Comment by skomskiy** [comment]
https://prnt.sc/uzlA5C5XRSM5
but now only the manifest file is synced

**Comment by skomskiy** [comment]
Fixed!
just added to shopify ignore assets/manifest.json
Thanks
