### ISSUE TITLE
feat: add possibililty for one root file entry

### ISSUE THREAD

**Issue by blanklob** [barrel/shopify-vite#148]
hey, is there a possible way we could have a root file entry? like for example one entrypoint file in the root of the theme:

```bash
assets
config
..
.shopifyignore
entry.js
package.json
```

Instead of a folder? that way I can import my css from the `entry.js` file and use it as entrypoint, I tried with current config options but it seamed impossible.

Inside the entry file I will call my components and modules.

```js
import './styles.css'
import './components'

...
```

thanks!

**Comment by blanklob** [comment]
@montalvomiguelo if you have any thoughts!

**Comment by montalvomiguelo** [comment]
Youness! 🙂 I just created a little [example](https://stackblitz.com/edit/vitejs-vite-gibfkm?file=vite.config.js) with one entry at the theme's root for you. Please let me know if that helps

**Comment by blanklob** [comment]
hey @montalvomiguelo here is my current example, I didn't manage to get it to work with your setup https://github.com/odestry/theme-starter/pull/2

**Comment by blanklob** [comment]
Do you also know how can i get rid of the auto generated dot vite folder thanks! 

<img width="326" alt="Capture d’écran 2024-08-17 à 22 53 46" src="https://github.com/user-attachments/assets/df45c62f-85cd-4635-80f8-d6e2787b4e3d">

**Comment by montalvomiguelo** [comment]
Let's try adding a `/` when loading the entry point since it's at the theme's root

```diff
-    {% render 'entry' with 'theme.entry.js' %}
+    {% render 'entry' with '/entry.theme.js' %}

```

Usually, I ignore the `.vite` stuff in my [.shopifyignore](https://github.com/montalvomiguelo/hydrogen-theme/blob/main/.shopifyignore#L19) file

**Comment by blanklob** [comment]
oh yeah that worked thanks as well, how do you usually handle deploying, do you ignore the assets folder? and have a CI with `shopify theme push` or use Github integration?

**Comment by montalvomiguelo** [comment]
I personally prefer using the Shopify GitHub Integration for deployments, with a standard theme directory structure. I don't ignore the `assets` folder.
