### ISSUE TITLE
There is a warning about the proload stylesheet rendered from the vite-tag.liquid which was auto-generated by vite-plugin-shopify

### ISSUE THREAD

**Issue by foloey** [barrel/shopify-vite#157]
**warning** in DevTools console panel:
> The resource http://*.myshopify.com/cdn/shop/t/7/assets/theme.CHIWAPFL.min.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

`theme.liquid`:
```liquid - theme.liquid
    {%- liquid
      render 'vite-tag' with 'theme.css', preload_stylesheet: true
      render 'vite-tag' with 'theme.js'
      if request.page_type contains 'customers/'
        render 'vite-tag' with 'customers.js'
      endif
    -%}
```

line-183 ~ line-185 of `/packages/vite-plugin-shopify/src/html.ts`:
```ts - /packages/vite-plugin-shopify/src/html.ts
// Generate a production stylesheet link tag for a style asset
const stylesheetTag = (fileName: string, versionNumbers: boolean): string =>
  `{{ ${assetUrl(fileName, versionNumbers)} | stylesheet_tag: preload: preload_stylesheet }}`
```

**Comment by montalvomiguelo** [comment]
@foloey, I couldn't reproduce the problem. The code functions as intended; the preload parameter enables Shopify to add the Link header for preloading the stylesheet.


<img width="1316" alt="Screenshot 2024-11-02 at 9 50 22 PM" src="https://github.com/user-attachments/assets/0b039715-c098-4fdb-b67c-ee1cf699f707">
