### ISSUE TITLE
Upgrade to Vite 6

### ISSUE THREAD

**Issue by bernier** [barrel/shopify-vite#160]
I'm getting some warnings after upgrading Vite from 5.4.10 to 6.0.2

_warn: incorrect peer dependency "vite@6.0.2"_

I rolled back to 5.4.10 due to these warnings.

**Comment by LuigiNicaPRO** [comment]
@montalvomiguelo  Someone needs to approve that pull request, right? Or we can install if from that branch?
I'm asking this because I can see "Approval not required" on the #161
