### ISSUE TITLE
Issue for theme app extensions

### ISSUE THREAD

**Issue by tommypepsi** [barrel/shopify-vite#57]
Hello!

Basically we are working on a theme app extension and when deploying, shopify complains that we can't have a json file in the assets folder because of the manifest.js file. Also we'd prefer to have a single js file that gets overwritten when we build instead of having a hash in the name with a new file every time. 

Our plugin config is like that:
```
plugins: [
  shopify({
    entrypointsDir: dirname(fileURLToPath(import.meta.url)) + "/storefront",
    themeRoot: dirname(fileURLToPath(import.meta.url)) + "/../../extensions/theme-extension-name"
  })
]
```

It all works fine until we add the config for the manifest and the file name:
```
build: {
  manifest: false,
  rollupOptions: {
    output: {
      entryFileNames: "[name].js"
    }
  }
},
```

Whenever we add a build config the vite-tag.liquid snippet stops updating. Anything we can do about that? :) 

Also, is it possible to have the script with a defer attribute in vite-tag.liquid? 

Thanks!

**Comment by montalvomiguelo** [comment]
Hi @tommypepsi :) 

The[ Shopify CLI ](https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started) can help to build theme app extensions more than this Plugin.

This Plugin is more like one of those [backend integrations ](https://vitejs.dev/guide/backend-integration.html#backend-integration) that rely on the `manifest.json` file to generate the script and link tags to load the assets in a backend system, in this case, a Shopify theme.



There is no need to use the `defer` attribute when loading ES modules; they are deferred automatically.

**Comment by tommypepsi** [comment]
@montalvomiguelo theme app extensions are a bit like mini themes, it has an `assets`, `blocks` (which replace sections for standard themes), `snippets` and `locales`. We are loading the main script of our app from the assets folder like you would do for a standard theme.

The plugin works perfectly fine in development mode but when it comes to deploying sadly the theme app extension doesn't allow us to deploy the asset folder with a json file for some reason. So we need to delete it manually every time we deploy. 

Since yesterday I figured we could probably use the lib feature of vite instead, but considering theme app extensions are a lot like small themes I'm sure this plugin could be useful for apps also.

And good to know for the defer with ES modules!

(You can close this issue if you don't think this is worth it 😅)

**Comment by montalvomiguelo** [comment]
@tommypepsi This is a super exciting use case I never thought of before!

Can you share a little example of leveraging this plugin for theme app extensions in a PR so we can learn more and explore this path together? 🙏

**Comment by montalvomiguelo** [comment]
@tommypepsi What if we used a [`.shopifyignore` ](https://shopify.dev/docs/themes/tools/cli#excluding-files-from-shopify-cli) file to ignore the `manifest.json` file during deployments?

**Comment by montalvomiguelo** [comment]
@tommypepsi I learned more about theme app extensions, and I am excited to share that I added 1 example to our docs 🎉

We can [clean up the assets directory before deploying the extension to Shopify](https://github.com/montalvomiguelo/theme-app-extension-vite/blob/main/package.json#L10)

```diff
+   "deploy": "run-s vite:build cleanup shopify:deploy",
    "vite:build": "vite build",
    "cleanup": "rimraf extensions/*/assets/*.{json,geetkeep}",
    "shopify:deploy": "shopify app deploy",

```
