### ISSUE TITLE
SCSS Variables [vite:css] [sass] Undefined variable.

### ISSUE THREAD

**Issue by andrewclo** [barrel/shopify-vite#58]
Hi, 

I am struggling to get SCSS compilation to work when running the `vite build` command. SCSS files with global variables work great when running `npm run dev`. `npm run build` errors with `[vite:css] [sass] Undefined `variable.`

```
import shopify from 'vite-plugin-shopify';

export default {
  plugins: [
    /* Plugin options are not required, defaults shown */
    shopify({
      // Root path to your Shopify theme directory (location of snippets, sections, templates, etc.)
      themeRoot: './',
      // Front-end source code directory
      sourceCodeDir: 'frontend',
      // Front-end entry points directory
      entrypointsDir: 'frontend/entrypoints',
      // Additional files to use as entry points (accepts an array of file paths or glob patterns)
      additionalEntrypoints: [],
    }),
  ],
};
```

<img width="349" alt="Screenshot 2023-03-07 at 3 32 11 PM" src="https://user-images.githubusercontent.com/1765900/223579486-2c2be07c-1edf-436e-8bea-188109fedbe1.png">

I appreciate any recommendations or advise.

**Comment by montalvomiguelo** [comment]
Hi @andrewclo ,

Have you installed the corresponding pre-processor in your project? 
https://vitejs.dev/guide/features.html#css-pre-processors

**Comment by andrewclo** [comment]
Hi @montalvomiguelo, yes I have. Here is a screenshot of package.json. 
<img width="748" alt="Screenshot 2023-03-07 at 3 52 34 PM" src="https://user-images.githubusercontent.com/1765900/223582308-1745d7f6-cf96-4528-8a5c-d22c5b025b5a.png">

This seems like a [similar issue with a different platform](https://github.com/storybookjs/storybook/issues/18670). I tried adding the `additionalData` parameter to the vite config file but still not able to compile as we have multiple scss files importing partials. Strange that it works perfect when serving from dev.

**Comment by montalvomiguelo** [comment]
Let's try using a different sass version, like in the following example:
https://github.com/barrel/shopify-vite/blob/main/themes/vite-shopify-example/package.json#L12

**Comment by andrewclo** [comment]
Still getting the same error with that version of sass. 
<img width="572" alt="Screenshot 2023-03-07 at 4 40 20 PM" src="https://user-images.githubusercontent.com/1765900/223589184-78af759c-8f43-434b-8918-08f84e018dbc.png">

`npm run dev` works well. 

This is what the scss folder structure looks like. `base.scss` imports the partials using `@import`. 
<img width="387" alt="Screenshot 2023-03-07 at 4 42 40 PM" src="https://user-images.githubusercontent.com/1765900/223589558-4f190c0c-6b00-4566-adc7-4a760b9a58db.png">

Appreciate any suggestions or advice.

**Comment by montalvomiguelo** [comment]
[@andrewclo](https://github.com/andrewclo) Maybe there is an issue somewhere in those partials. Can you import one partial at a time from your "base.scss" to find it?

I cannot reproduce the issue; I created a "variable.scss" partial and imported it into my "theme.scss" to consume the variables. The build runs as expected.

https://user-images.githubusercontent.com/5134470/223601141-422da11b-2858-4c52-b9d6-54369252595f.mp4

**Comment by andrewclo** [comment]
Appreciate the support @montalvomiguelo and @andyxmas. I was able to get the project to build by simplifying the SCSS imports. Still very confused as to why this builds fine. 

`@import 'helpers/helpers';

.footer__wrapper {
  background: $color-black;
}`

However if I move the .footer__wrapper CSS to another partial and include it in the main SCSS entry point such as this: 
`@import 'helpers/helpers';
@import 'partials/footer';
`
I get build errors. 
<img width="582" alt="Screenshot 2023-03-08 at 10 03 52 AM" src="https://user-images.githubusercontent.com/1765900/223793960-89a5a3c8-bcbe-4abc-9eee-c2cc6ced1907.png">

**Comment by andrewclo** [comment]
> @andrewclo just in case its helpful, this is our SCSS setup. In vite.config.js:
> 
> ```
>   css: {
>     preprocessorOptions: {
>       scss: {
>         additionalData: `@import '@/scss/settings/.settings.scss';`
>       }
>     }
>   }
> ```
> 
> `.settings.scss` imports all the partials with variables etc. Works for us on dev & production builds, with all the scss variables/mixins etc available to each scss file.

Thanks for this @andyxmas. What does your main entrypoint scss file look like? Does it have any @import statements?

**Comment by andyxmas** [comment]
> > @andrewclo just in case its helpful, this is our SCSS setup. In vite.config.js:
> > ```
> >   css: {
> >     preprocessorOptions: {
> >       scss: {
> >         additionalData: `@import '@/scss/settings/.settings.scss';`
> >       }
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `.settings.scss` imports all the partials with variables etc. Works for us on dev & production builds, with all the scss variables/mixins etc available to each scss file.
> 
> Thanks for this @andyxmas. What does your main entrypoint scss file look like? Does it have any @import statements?

main entry file has just this `@import '@/scss/global/.global';`

then the `_.global.scss`  file imports multiple partials in the same way. 

We're then using the `modules` functionality, and within each module, have scss files that are loaded independantly, but have access to all of these variables and mixins etc.

**Comment by andrewclo** [comment]
Thanks @andyxmas. I copied your structure and all is working well. Thanks for the help.
