### ISSUE TITLE
snippetFile option

### ISSUE THREAD

**Issue by slavamak** [barrel/shopify-vite#63]
Thanks for the new version of the plugin! While testing, I found a problem with using a custom name for snippet. It seems we also need to replace `vite-tag` here

https://github.com/barrel/shopify-vite/blob/1c63fd149ca14ee47d67abac6a06accc225a7d08/packages/vite-plugin-shopify/src/html.ts#L152

**Comment by montalvomiguelo** [comment]
🙏 Thanks for reporting this bug @slavamak . Good catch! I'm currently working on fixing it.
