### ISSUE TITLE
Handling 3rd party app assets

### ISSUE THREAD

**Issue by hcmlopes** [barrel/shopify-vite#68]
I had to spend a little time reading documentation and figuring it out however there could also be better ways of doing this so I wanted to share and get feedback.

When using shopify's github integration the integration will sync back files created by other 3rd party apps into the sync folder. The problem was that the assets folder gets deleted and recreated with the `frontend/entrypoints` as well as `public` contents.

My Solution:
1. Add build configuration for rollupOptions which will add an identifier to the generated filenames
2. Copy all of the contents from the assets folder while excluding anything fitting our pattern into `frontend/assets` before the folder is deleted 
3. Update config to use the new `frontend/assets` folder as the public folder

For step 2, I used `rollup-plugin-copy` which supports negation patterns to excluded the automatically generated files which will be recreated by the shopify-vite plugin

Here is the example configuration:
```js
import shopify from 'vite-plugin-shopify'
import copy from 'rollup-plugin-copy'

const namespace = 'vite'
export default {
  build: {
    rollupOptions: {
      output: {
        entryFileNames: `[name]-${namespace}-[hash].js`,
        chunkFileNames: `[name]-${namespace}-[hash].js`,
        assetFileNames: `[name]-${namespace}-[hash].[ext]`
      },
    }
  },
  publicDir: 'frontend/assets',
  plugins: [
    copy({
      targets: [
        {
          src: ['assets/*', `!**/*${namespace}*.*`], dest: "frontend/assets"
        }
      ]
    }),
    shopify()
  ]
}
```
Any feedback would be appreciated.

**Comment by montalvomiguelo** [comment]
@hcmlopes  Thanks for bringing this up! It could be a common problem, and sharing possible ways to solve it can be helpful to the community. 

What if we eliminated the copy step to avoid having duplicate files? Then we could tell Vite not to empty the `outDir` so the `assets` folder stays as-is, and then we could run a custom `cleanup` script to delete our previous dist files before building new ones with Vite.

```diff
import { defineConfig } from 'vite'
import shopify from 'vite-plugin-shopify'

const namespace = 'vite'
export default defineConfig({
  plugins: [
    shopify()
  ],
  build: {
+   emptyOutDir: false,
    rollupOptions: {
      output: {
        entryFileNames: `[name]-${namespace}-[hash].js`,
        chunkFileNames: `[name]-${namespace}-[hash].js`,
        assetFileNames: `[name]-${namespace}-[hash].[ext]`
      },
    }
  }
})

```

```diff
{
  "devDependencies": {
+   "rimraf": "^4.4.0",
    "vite": "^4.2.0",
    "vite-plugin-shopify": "^2.0.1"
  },
  "scripts": {
    "dev": "vite",
+   "build": "npm run cleanup && vite build",
+   "cleanup": "rimraf 'assets/*-vite-*' 'assets/manifest.json'"
  }
}

```

**Comment by dan-gamble** [comment]
I had to tackle this too! Was quite tricky to handle but I ended up adding a [vite-shopify-plugin-clean](https://gist.github.com/dan-gamble/cf1b695efc2871c9d17140de9cabf782) module which would only clean files that are in the manifest and would leave any other 3rd party files. What you have looks a lot smaller and cleaner 😅

**Comment by montalvomiguelo** [comment]
@hcmlopes, that's a very feasible solution. We could leverage the Plugin that @dan-gamble shared to clean only files in the manifest. 

Thanks a lot for this @dan-gamble 🙏 
https://www.npmjs.com/package/@by-association-only/vite-plugin-shopify-clean

```js
import shopify from 'vite-plugin-shopify'
import cleanup from '@by-association-only/vite-plugin-shopify-clean'

export default {
  build: {
    emptyOutDir: false
  },
  plugins: [
    cleanup(),
    shopify()
  ]
}
```

**Comment by hcmlopes** [comment]
@montalvomiguelo wow did you just make that into a npm package?

**Comment by montalvomiguelo** [comment]
@hcmlopes I did not lol, @dan-gamble made his Plugin public ❤️

**Comment by hcmlopes** [comment]
thank you @dan-gamble 🎉

**Comment by dan-gamble** [comment]
I could open source what we have. I was planning to once it was finally done but we've not even properly tried it on projects yet!

I've changed quite a lot of the `modules` plugin as well. I appreciate that I can see you're going away from that though so it might not be as valuable now.

**Comment by montalvomiguelo** [comment]
@dan-gamble, Let us know if there is anything we can help with (docs, testing, etc.) when you open-source it!

**Comment by Eben-Hafkamp** [comment]
Does anybody else have a bad experience of using the GitHub integration? As in it creates way too many unintelligible commits. My solution is to just run the `pull` command provided by the theme cli to check the diff and make a more informed chore commit before starting the next feature.

**Comment by kenji-twp** [comment]
hey @dan-gamble, are you planning on open sourcing your vite plugin shopify clean? I upgraded to vite 5 and the plugin still uses vite 4. Do you mind if I continue from where you left off in a separate repo?

**Comment by truemoroz** [comment]
We need something to work with vite 5
@dan-gamble Will you update your plugin?
@knjshimi Do you have solution?
