### ISSUE TITLE
theme css file is not loading in app extension

### ISSUE THREAD

**Issue by dotamir** [barrel/shopify-vite#97]
Hi. Thanks for your great plugin. It really helped me a lot.

I found out an issue today. theme css file is not loading in app extension when I make a build. JS file is working and it is appearing in the dev store, but CSS styles are not loading. However it's working well when I'm developing using `pnpm dev` but when I deploy the extension to Shopify, CSS is not working.

I had to do a tricky workaround for now and manually add theme.css file in the block liquid file and it's working this way.

Any idea what would be the issue?

Here is my vite configs:
```js
import path from "path"
import { defineConfig } from 'vite'
import shopify from 'vite-plugin-shopify'
import react from '@vitejs/plugin-react'
import cleanup from '@by-association-only/vite-plugin-shopify-clean';

export default defineConfig({
  plugins: [
    shopify({
      themeRoot: 'extensions/app-extension',
    }),
    cleanup({
      manifestFileName: 'manifest.json',
      themeRoot: 'extensions/app-extension',
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./frontend"),
    },
  },
})
```

Thanks in advance.

**Comment by montalvomiguelo** [comment]
Hi @dotamir 

I created this [theme-extension](https://github.com/montalvomiguelo/theme-extension-vite/tree/main) with the plugins in this repo, and I see styles loading as expected. Can you check the setup?

**Comment by dotamir** [comment]
Hi @montalvomiguelo 
Yes setup looks the same and as I have mentioned it is working when I run the server using `pnpm dev`. Only deploying builds to Shopify is not working.

Here is my main liquid block as well

```liquid
<div id="shoppyc-clickcollect">
  {% liquid
    # Relative to entrypointsDir
    render 'vite-tag' with 'theme.css'
    render 'vite-tag' with 'theme.jsx'
  %}
</div>
```

**Comment by montalvomiguelo** [comment]
@dotamir  Everything looks good to me here. Could you let me know if you're running deploy from the extension's directory?

https://github.com/barrel/shopify-vite/assets/5134470/e85e90d1-c0e2-4562-9b69-89b596f50995

**Comment by dotamir** [comment]
@montalvomiguelo Thanks for your reply. I do have a different structure for my project so I'm not running the deploy command from the extension. But the only issue is when I deploy the extension, while I'm developing it's working well without issue and I see the CSS files are working well. But the built css files using the build command are not working.

So I'm curious that how only the files after build and pushing to Shopify is not working?

**Comment by montalvomiguelo** [comment]
Could you provide a [minimal setup](https://stackblitz.com/edit/vitejs-vite-xbn1ka) with some code you think is ok to share?

**Comment by iskurbanov** [comment]
You can use the [cssInjectedByJsPlugin ](https://www.npmjs.com/package/vite-plugin-css-injected-by-js) as a work around.

**Comment by dotamir** [comment]
@iskurbanov Your solution worked! Thank you so much. I will close this issue
